### ISSUE TITLE
Can not download model checkpoint

### ISSUE THREAD

**Issue by RockXeng** [bozhenhhu/DefectSAM#1]
can not open it : https://drive.google.com/file/d/1VX8O7R7UCUg8In9SShLxK1lVRi97luEf/view?usp=sharing

**Comment by bozhenhhu** [comment]
Hi, I can open it as previously. If you can not use Google Drive, I can upload it to the Baidu cloud disk.

**Comment by bozhenhhu** [comment]
链接：https://pan.baidu.com/s/1tWQou4zqKyy1Dkjk6xS6RQ 
提取码：zsq0

**Comment by RockXeng** [comment]
Thanks, I got it!
